var config = {};
config.symbols = [{
  "tradingpair": "more_eos",
  "contract": "eosiomoreone",
  "symbol": "MORE",
  "price_precision": 5,
  "currency_precision": 4
}, {
  "tradingpair": "epra_eos",
  "contract": "epraofficial",
  "symbol": "EPRA",
  "price_precision": 6,
  "currency_precision": 4
}, {
  "tradingpair": "dab_eos",
  "contract": "eoscafekorea",
  "symbol": "DAB",
  "price_precision": 6,
  "currency_precision": 4
}, {
  "tradingpair": "evr_eos",
  "contract": "eosvrtokenss",
  "symbol": "EVR",
  "price_precision": 6,
  "currency_precision": 4
}, {
  "tradingpair": "deos_eos",
  "contract": "thedeosgames",
  "symbol": "DEOS",
  "price_precision": 6,
  "currency_precision": 4
}, {
  "tradingpair": "pgl_eos",
  "contract": "prospectorsg",
  "symbol": "PGL",
  "price_precision": 4,
  "currency_precision": 4
}, {
  "tradingpair": "wecash_eos",
  "contract": "weosservices",
  "symbol": "WECASH",
  "price_precision": 7,
  "currency_precision": 4
}, {
  "tradingpair": "itecoin_eos",
  "contract": "itecointoken",
  "symbol": "ITECOIN",
  "price_precision": 6,
  "currency_precision": 4
}, {
  "tradingpair": "tea_eos",
  "contract": "linzongsheng",
  "symbol": "TEA",
  "price_precision": 7,
  "currency_precision": 4
}, {
  "tradingpair": "faid_eos",
  "contract": "eosfaidchain",
  "symbol": "FAID",
  "price_precision": 6,
  "currency_precision": 4
}, {
  "tradingpair": "lucky_eos",
  "contract": "eoslucktoken",
  "symbol": "LUCKY",
  "price_precision": 4,
  "currency_precision": 4
}, {
  "tradingpair": "luck_eos",
  "contract": "eosluckchain",
  "symbol": "LUCK",
  "price_precision": 6,
  "currency_precision": 4
}, {
  "tradingpair": "tpt_eos",
  "contract": "tokendapppub",
  "symbol": "TPT",
  "price_precision": 6,
  "currency_precision": 4
}, {
  "tradingpair": "pub_eos",
  "contract": "publytoken11",
  "symbol": "PUB",
  "price_precision": 6,
  "currency_precision": 4
}, {
  "tradingpair": "btn_eos",
  "contract": "eosbuttonbtn",
  "symbol": "BTN",
  "price_precision": 7,
  "currency_precision": 4
}, {
  "tradingpair": "shape_eos",
  "contract": "gmaslaunches",
  "symbol": "SHAPE",
  "price_precision": 6,
  "currency_precision": 4
}, {
  "tradingpair": "cat_eos",
  "contract": "tokenbyeocat",
  "symbol": "CAT",
  "price_precision": 6,
  "currency_precision": 4
}, {
  "tradingpair": "toe_eos",
  "contract": "talkoneos123",
  "symbol": "TOE",
  "price_precision": 6,
  "currency_precision": 4
}, {
  "tradingpair": "dice_eos",
  "contract": "betdicetoken",
  "symbol": "DICE",
  "price_precision": 6,
  "currency_precision": 4
}, {
  "tradingpair": "roy_eos",
  "contract": "eosroyaleroy",
  "symbol": "ROY",
  "price_precision": 7,
  "currency_precision": 4
}, {
  "tradingpair": "seven_eos",
  "contract": "xxxsevensxxx",
  "symbol": "SEVEN",
  "price_precision": 7,
  "currency_precision": 4
}, {
  "tradingpair": "pso_eos",
  "contract": "cryptopesosc",
  "symbol": "PSO",
  "price_precision": 6,
  "currency_precision": 4
}, {
  "tradingpair": "oct_eos",
  "contract": "octtothemoon",
  "symbol": "OCT",
  "price_precision": 4,
  "currency_precision": 4
}, {
  "tradingpair": "cet_eos",
  "contract": "eosiochaince",
  "symbol": "CET",
  "price_precision": 5,
  "currency_precision": 4
}, {
  "tradingpair": "horus_eos",
  "contract": "horustokenio",
  "symbol": "HORUS",
  "price_precision": 5,
  "currency_precision": 4
}, {
  "tradingpair": "karma_eos",
  "contract": "therealkarma",
  "symbol": "KARMA",
  "price_precision": 6,
  "currency_precision": 4
}, {
  "tradingpair": "chl_eos",
  "contract": "challengedac",
  "symbol": "CHL",
  "price_precision": 7,
  "currency_precision": 4
}, {
  "tradingpair": "black_eos",
  "contract": "eosblackteam",
  "symbol": "BLACK",
  "price_precision": 5,
  "currency_precision": 4
}, {
  "tradingpair": "eosdac_eos",
  "contract": "eosdactokens",
  "symbol": "EOSDAC",
  "price_precision": 5,
  "currency_precision": 4
}, {
  "tradingpair": "edna_eos",
  "contract": "ednazztokens",
  "symbol": "EDNA",
  "price_precision": 6,
  "currency_precision": 4
}, {
  "tradingpair": "atd_eos",
  "contract": "eosatidiumio",
  "symbol": "ATD",
  "price_precision": 6,
  "currency_precision": 4
}, {
  "tradingpair": "meetone_eos",
  "contract": "eosiomeetone",
  "symbol": "MEETONE",
  "price_precision": 6,
  "currency_precision": 4
}, {
  "tradingpair": "wizz_eos",
  "contract": "wizznetwork1",
  "symbol": "WIZZ",
  "price_precision": 7,
  "currency_precision": 4
}, {
  "tradingpair": "iq_eos",
  "contract": "everipediaiq",
  "symbol": "IQ",
  "price_precision": 5,
  "currency_precision": 3
}, {
  "tradingpair": "add_eos",
  "contract": "eosadddddddd",
  "symbol": "ADD",
  "price_precision": 6,
  "currency_precision": 4
}, {
  "tradingpair": "boid_eos",
  "contract": "boidcomtoken",
  "symbol": "BOID",
  "price_precision": 7,
  "currency_precision": 4
}, {
  "tradingpair": "eox_eos",
  "contract": "eoxeoxeoxeox",
  "symbol": "EOX",
  "price_precision": 7,
  "currency_precision": 4
}, {
  "tradingpair": "esb_eos",
  "contract": "esbcointoken",
  "symbol": "ESB",
  "price_precision": 7,
  "currency_precision": 4
}, {
  "tradingpair": "poor_eos",
  "contract": "poormantoken",
  "symbol": "POOR",
  "price_precision": 7,
  "currency_precision": 4
}, {
  "tradingpair": "eosnts_eos",
  "contract": "eosninetiess",
  "symbol": "EOSNTS",
  "price_precision": 6,
  "currency_precision": 4
}, {
  "tradingpair": "can_eos",
  "contract": "eoscancancan",
  "symbol": "CAN",
  "price_precision": 4,
  "currency_precision": 4
}, {
  "tradingpair": "trybe_eos",
  "contract": "trybenetwork",
  "symbol": "TRYBE",
  "price_precision": 5,
  "currency_precision": 4
}, {
  "tradingpair": "wizbox_eos",
  "contract": "wizboxairdro",
  "symbol": "WIZBOX",
  "price_precision": 4,
  "currency_precision": 0
}];
module.exports = config;